export const onGoingList = [
    {
        id: 1,
        title: 'Strange Vintage : 오광대의 기묘한 탈',
        text: '',
        image: process.env.PUBLIC_URL+'img/works/main/on1.jpg',
    },
    {
        id: 2,
        title: '안녕, 모란',
        text: '국립고궁박물관',
        image: 'img/works/main/on2.jpg'
    },
    {
        id: 3,
        title: '호모 사피엔스 : 진화∞관계&미래?',
        text: '국립중앙박물관',
        image: 'img/works/main/on3.png'
    },
    {
        id: 4,
        title: '성덕대왕신종 입체음향 실감 콘텐츠 ‘화답’',
        text: '국립경주박물관',
        image: 'img/works/main/on4.png'
    },
    {
        id: 5,
        title: '모래섬, 비행장, 빌딩숲 여의도',
        text: '서울역사박물관',
        image: 'img/works/main/on5.jpg'
    },
    {
        id: 6,
        title: '열린 보존과학실',
        text: '국립민속박물관 보존과학스튜디오',
        image: 'img/works/main/on6.jpg'
    },
]

export const archiveList = [
    {
        id: 1,
        title: '등록문화재, 광화문에서 보다',
        text: '대한민국역사박물관',
        image: 'img/works/main/arc1.jpg'
    },
    {
        id: 2,
        title: '백제 산수문전 - \n 과거의 흔적, 색을 찾다',
        text: '국립부여박물관',
        image: 'img/works/main/arc2.jpg'
    },
    {
        id: 3,
        title: '메이드 인 청계천\n미디어아트 x 세운상가',
        text: '청계천박물관',
        image: 'img/works/main/arc3.jpg'
    },
    {
        id: 4,
        title: 'Small Change in Seoul',
        text: '서울 도시 건축 전시관',
        image: 'img/works/main/arc4.jpg'
    },
    {
        id: 5,
        title: '한양도성의 훼손과 탄생',
        text: '한양도성박물관',
        image: 'img/works/main/arc5.jpg'
    },
    {
        id: 6,
        title: '숙종대왕 호시절에',
        text: '국립고궁박물관',
        image: 'img/works/main/arc6.jpg'
    },
    {
        id: 7,
        title: '오색영롱 - 한국 고대 유리와 신라',
        text: '국립경주박물관',
        image: 'img/works/main/arc7.jpg'
    },
    {
        id: 8,
        title: '오월 그날이 다시 오면',
        text: '대한민국역사박물관',
        image: 'img/works/main/arc8.jpg'
    },
    {
        id: 9,
        title: '서울은 소설의 주인공이다',
        text: '서울역사박물관',
        image: 'img/works/main/arc9.jpg'
    },
    {
        id: 10,
        title: '수표교水標橋 - 한양에 비가 내리면',
        text: '청계천박물관',
        image: 'img/works/main/arc10.jpg'
    },
    {
        id: 11,
        title: '인간, 물질 그리고 변형\n핀란드 디자인 10 000년',
        text: '국립중앙박물관',
        image: 'img/works/main/arc11.jpg'
    },
    {
        id: 12,
        title: '성균관과 반촌',
        text: '서울역사박물관',
        image: 'img/works/main/arc12.jpg'
    },
    {
        id: 13,
        title: '소리, 역사를 담다',
        text: '대한민국역사박물관',
        image: 'img/works/main/arc13.jpg'
    },
    {
        id: 14,
        title: '四神사신이 호위하사, 백제 능산리 1호\n東下塚동하총',
        text: '국립부여박물관',
        image: 'img/works/main/arc14.jpg'
    },
    {
        id: 15,
        title: '북촌, 열한 집의 오래된 기억',
        text: '서울역사박물관',
        image: 'img/works/main/arc15.jpg'
    },
    {
        id: 16,
        title: '여의도공원 비행기 영상 쇼\n어느 소년 광복군의 비행\'',
        text: '서울여의도공원',
        image: 'img/works/main/arc16.jpg'
    },
    {
        id: 17,
        title: '무병장수의 별 노인성, 제주를 비추다',
        text: '국립제주박물관',
        image: 'img/works/main/arc17.jpg'
    },
    {
        id: 18,
        title: '서울과 평양의 3·1운동',
        text: '대한민국역사박물관',
        image: 'img/works/main/arc18.jpg'
    },
    {
        id: 19,
        title: '경강 - 광나루에서 양화진까지',
        text: '서울역사박물관',
        image: 'img/works/main/arc19.jpg'
    },
    {
        id: 20,
        title: '메이드 인 청계천 대중문화,\n‘빽판’의 시대',
        text: '청계천박물관',
        image: 'img/works/main/arc20.jpg'
    },
    {
        id: 21,
        title: '그들이 꿈꾸었던 나라',
        text: '대한민국역사박물관',
        image: 'img/works/main/arc21.jpg'
    },
    {
        id: 22,
        title: '개태사開泰寺 - \n 태평성대 고려高麗를 열다',
        text: '국립부여박물관',
        image: 'img/works/main/arc22.jpg'
    },
    {
        id: 23,
        title: '다시 보는 청계천 - \n 구와바라 시세이 사진전',
        text: '청계천박물관',
        image: 'img/works/main/arc23.jpg'
    },
];



export const onGoingDetail = [
    {},
    {
        id: 1,
        title: "Strange Vintage : 오광대의 기묘한 탈",
        subTitle: "",
        h2: "Strange Vintage : 오광대의 기묘한 탈",
        h3: "우리나라 전통 가면극 '통영오광대'의 혼합현실 체험을 위한 \n 이머시브 마당놀이 실감콘텐츠 입니다",
        location: "-",
        date: "2021, 11",
        category: "Immersive Space \n Interactive Art \n Projection Mapping \n Motion Graphic",
        role: "Planning, Producing, Making",
        iframe: [

        ],
        still: "STILLS",
        images: [
            "/img/works/ongoing/1/1.jpg",
            "/img/works/ongoing/1/2.jpg",
            "/img/works/ongoing/1/3.jpg",
            "/img/works/ongoing/1/4.jpg",
            "/img/works/ongoing/1/5.jpg",
        ],
        headerImage: "/img/works/ongoing/1/1-1.jpg",
        background: "bg bg1",
    },
    {
        id: 2,
        title: "안녕, 모란",
        subTitle: "국립고궁박물관 \n National Palace Museum",
        h2: "안녕, 모란",
        h3: "우리나라에 들어온 삼국시대부터 조선시대에 이르기까지 왕실과 민간을 \n 막론하며 사랑받은 꽃 모란. 그 중 조선 왕실에서 모란이 향유하는 \n 다양한 상징을 소개하는 특별전입니다.",
        location: "국립고궁박물관",
        date: "2021, 07",
        category: "Immersive Space \n Interactive Art \n Projection Mapping \n Motion Graphic \n Documentary Film",
        role: "Planning, Producing, Making",
        still: "STILLS",
        iframe: [

        ],
        images: [
            "/img/works/ongoing/2/1.jpg",
            "/img/works/ongoing/2/2.jpg",
            "/img/works/ongoing/2/3.jpg",
            "/img/works/ongoing/2/4.jpg",
            "/img/works/ongoing/2/5.jpg",
            "/img/works/ongoing/2/6.jpg",
            "/img/works/ongoing/2/7.jpg",
            "/img/works/ongoing/2/8.jpg",
            "/img/works/ongoing/2/9.jpg",
            "/img/works/ongoing/2/10.jpg",
            "/img/works/ongoing/2/11.jpg",
            "/img/works/ongoing/2/12.jpg",
        ],
        headerImage: "/img/works/ongoing/2/1-1" +
            ".jpg",
        background: "bg bg2",
    },
    {
        id: 3,
        title: "호모 사피엔스 : 진화∞관계&미래?",
        subTitle: "국립중앙박물관 \n National Museum of Korea",
        h2: "호모 사피엔스 : 진화∞관계&미래?",
        h3: "국립중앙박물관 특별 전시 [호모 사피엔스 : 진화∞ 관계& 미래?]에서는 \n 다양한 시각으로 호모사피엔스의 과장되지 않은 실체를 직시해 보고자 합니다. \n 또 진화과정에서 맺어 온 여러 생물종들과의 관계를 성찰하는 한편, \n 앞으로 맞이하게 될 미래를 준비하는 우리의 자세를 \n 고민해보는 기회이기를 희망합니다.",
        location: "국립중앙박물관",
        date: "2021, 05",
        category: "Immersive Space \n Interactive Art \n 3D Projection Mapping \n 3D Motion Capture \n Motion Graphic",
        role: "Planning, Producing, Making \n System Design, Development",
        iframe: [
            "https://www.youtube.com/embed/I8Ys1fNF43I",
        ],
        still: "STILLS",
        images: [
            "/img/works/ongoing/3/1.jpg",
            "/img/works/ongoing/3/2.jpg",
            "/img/works/ongoing/3/3.jpg",
            "/img/works/ongoing/3/4.jpg",
            "/img/works/ongoing/3/5.jpg",
            "/img/works/ongoing/3/6.jpg",
            "/img/works/ongoing/3/7.jpg",
            "/img/works/ongoing/3/8.jpg",
            "/img/works/ongoing/3/9.jpg",
            "/img/works/ongoing/3/10.jpg",
            "/img/works/ongoing/3/11.jpg",
            "/img/works/ongoing/3/12.jpg",
        ],
        headerImage: "/img/works/ongoing/3/1-1.jpg",
        background: "bg bg3",
    },
    {
        id: 4,
        title: "성덕대왕신종 입체음향 실감 콘텐츠 ‘화답’",
        subTitle: "국립경주박물관 \n National Museum of Korea",
        h2: "성덕대왕신종 입체음향 실감 콘텐츠 ‘화답’",
        h3: "성덕대왕신종 주조 1250주년을 맞아 조성된 '성덕대왕신종 소리체험관' \n 성덕대왕신종과 관련된 설화를 바탕으로 구성된 판타지 스토리와 \n 신종의 실제 맑고 웅장한 소리를 체험할 수 있는 상설전입니다.",
        location: "국립경주박물관",
        date: "2021, 03",
        category: "Immersive Space \n Immersive Sound \n 3D Projection Mapping \n Motion Graphic",
        role: "Planning, Producing, Making \n System Design",
        iframe: [

        ],
        still: "STILLS",
        images: [
            "/img/works/ongoing/4/1.jpg",
            "/img/works/ongoing/4/2.jpg",
            "/img/works/ongoing/4/3.jpg",
            "/img/works/ongoing/4/4.jpg",
            "/img/works/ongoing/4/5.jpg",
            "/img/works/ongoing/4/6.jpg",
            "/img/works/ongoing/4/7.jpg",
            "/img/works/ongoing/4/8.jpg",
            "/img/works/ongoing/4/9.jpg",
            "/img/works/ongoing/4/10.jpg",
            "/img/works/ongoing/4/11.jpg",
        ],
        headerImage: "/img/works/ongoing/4/1-1.jpg",
        background: "bg bg4",
    },
    {
        id: 5,
        title: "모래섬, 비행장, 빌딩숲 여의도",
        subTitle: "서울역사박물관 \n Seoul Museum of History",
        h2:  "모래섬, 비행장, 빌딩숲 여의도",
        h3: "서울 근현대사의 주요 무대였던 여의도. 여의도의 역사를 살펴보며 \n 서울이 간직한 우리의 이야기를 되새기는 특별전입니다.",
        location: "서울역사박물관",
        date: "2021, 05",
        category: "Immersive Space \n Projection \n Mapping \n Motion Graphic \n Infographic Video",
        role: "Planning, Producing, Making \n System Design, Development",
        iframe: [
            "https://www.youtube.com/embed/xKfKVheoXqw",
        ],
        still: "STILLS",
        images: [
            "/img/works/ongoing/5/1.jpg",
            "/img/works/ongoing/5/2.jpg",
            "/img/works/ongoing/5/3.jpg",
            "/img/works/ongoing/5/4.jpg",
            "/img/works/ongoing/5/5.jpg",
            "/img/works/ongoing/5/6.jpg",
            "/img/works/ongoing/5/7.jpg",
            "/img/works/ongoing/5/8.jpg",
            "/img/works/ongoing/5/9.jpg",
            "/img/works/ongoing/5/10.jpg",
            "/img/works/ongoing/5/11.jpg",
            "/img/works/ongoing/5/12.jpg",
            "/img/works/ongoing/5/13.jpg",
            "/img/works/ongoing/5/14.jpg",
        ],
        headerImage: "/img/works/ongoing/5/1-1.jpg",
        background: "bg bg5",
    },
    {
        id: 6,
        title: "열린 보존과학실",
        subTitle: "국립민속박물관 보존과학스튜디오 \n National Folk Museum of Korea",
        h2: "열린 보존과학실",
        h3: "문화재 병원이라 할 수 있는 보존과학실을 간접 체험할 수 있는 탐구 \n 놀이 공간. 박물관 유물의 보존처리 과정에서 수집된 유해생물과 환경에 \n 대한 자료를 기초로 보존 환경에 대한 이해를 돕는 전시입니다.",
        location: "국립민속박물관 보존과학스튜디오",
        date: "2021, 05",
        category: "Interactive Media \n Immersive Sound \n Graphic, Infographic Video",
        role: "Planning, Producing, Shoot \n Making, Development",
        iframe: [

        ],
        still: "STILLS",
        images: [
            "/img/works/ongoing/6/1.jpg",
            "/img/works/ongoing/6/2.jpg",
            "/img/works/ongoing/6/3.jpg",
            "/img/works/ongoing/6/4.jpg",
            "/img/works/ongoing/6/5.jpg",
            "/img/works/ongoing/6/6.jpg",
            "/img/works/ongoing/6/7.jpg",
            "/img/works/ongoing/6/8.jpg",
            "/img/works/ongoing/6/9.jpg",
            "/img/works/ongoing/6/10.jpg",
            "/img/works/ongoing/6/11.jpg",
            "/img/works/ongoing/6/12.jpg",
        ],
        headerImage: "/img/works/ongoing/6/1-1.jpg",
        background: "bg bg6",
    }
];

export const archiveDetail = [
    {},
    {
        id: 1,
        title: "등록문화재, 광화문에서 보다",
        subTitle: "대한민국역사박물관 \n Museum of Korean History",
        h2: "등록문화재, 광화문에서 보다",
        h3: "우리 일상 곳곳에 근현대사의 흔적을 담고 있는 소중한 문화유산, \n 국가등록문화재. 올해 20주년을 맞이하여 문화재마다 담긴 특별한 \n 이야기를 소개하고, 흔적의 가치에 대해서도 되돌아보는 특별전입니다.",
        location: "대한민국역사박물관",
        date: "2021, 04",
        category: "Interactive Media, \n Virtual Reality, \n Projection Mapping",
        role: "Planning, Producing, Making \n System Design, Development",
        iframe: [
            "https://www.youtube.com/embed/nr2jDuRmams",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/1/1.jpg",
            "/img/works/archive/1/2.jpg",
            "/img/works/archive/1/3.jpg",
            "/img/works/archive/1/4.jpg",
            "/img/works/archive/1/5.jpg",
            "/img/works/archive/1/6.jpg",
            "/img/works/archive/1/7.jpg",
            "/img/works/archive/1/8.jpg",
            "/img/works/archive/1/9.jpg",
            "/img/works/archive/1/10.jpg",
            "/img/works/archive/1/11.jpg",
            "/img/works/archive/1/12.jpg",
            "/img/works/archive/1/13.jpg",
        ],
        headerImage: "/img/works/archive/1/1-1.jpg",
    },
    {
        id: 2,
        title: "백제 산수문전 - 과거의 흔적, 색을 찾다",
        subTitle: "국립부여박물관 \n Buyeo National Museum",
        h2: "백제 산수문전 - 과거의 흔적, 색을 찾다",
        h3: "백제문화의 정수(精髓)로 손꼽히는 부여박물관의 대표 소장품 \n '백제 문양전' 을 감상하고, 백제인의 이상향의 공간을 구현하여 \n 관람객에게 힐링을 전하는 특별전입니다.",
        location: "국립부여박물관",
        date: "2020, 12",
        category: "Immersive Space, Interactive Art, \n Interaction Lighting, \n 3D Projection Mapping, \n Motion Graphic",
        role: "Planning, Producing, Making \n System Design, Development",
        iframe: [
            "https://www.youtube.com/embed/OkpvYbnI1sQ",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/2/1.jpg",
            "/img/works/archive/2/2.jpg",
            "/img/works/archive/2/3.jpg",
            "/img/works/archive/2/4.jpg",
            "/img/works/archive/2/5.jpg",
            "/img/works/archive/2/6.jpg",
            "/img/works/archive/2/7.jpg",
            "/img/works/archive/2/8.jpg",
        ],
        headerImage: "/img/works/archive/2/1-1.jpg",
    },
    {
        id: 3,
        title: "메이드 인 청계천 \n 미디어아트 x 세운상가",
        subTitle: "청계천박물관 \n Cheonggyecheon Museum",
        h2: "메이드 인 청계천 \n 미디어아트 x 세운상가",
        h3: "1960-80년대 기술력의 상징적 주체이면서, 미디어 아트의 태동과 \n 전개 과정에 자리한 세운상가의 이면을 조명하는 특별전입니다.",
        location: "청계천박물관",
        date: "2020, 11",
        category: "Interactive Media, \n Documentary Film",
        role: "Planning, Producing, Shoot \n Making, Development",
        iframe: [
            "https://www.youtube.com/embed/c6UwKpX-Zes",
            "https://www.youtube.com/embed/M4epx6UzR3I",
            "https://www.youtube.com/embed/7BTJ93hPOrQ",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/3/1.jpg",
            "/img/works/archive/3/2.jpg",
            "/img/works/archive/3/3.jpg",
            "/img/works/archive/3/4.jpg",
            "/img/works/archive/3/5.jpg",
            "/img/works/archive/3/6.jpg",
            "/img/works/archive/3/7.jpg",
            "/img/works/archive/3/8.jpg",
            "/img/works/archive/3/9.jpg",
            "/img/works/archive/3/10.jpg",
        ],
        headerImage: "/img/works/archive/3/1-1.jpg",
    },
    {
        id: 4,
        title: "Small Change in Seoul",
        subTitle: "서울 도시 건축 전시관 \n Seoul City Architecture Exhibition Hall",
        h2: "Small Change in Seoul",
        h3: "서울 안에서 일어나고 있는 공간의 변화와 공간간의 관계, 그로인해 \n 생성되는 이 도시와 시민의 관계에 대한 이야기까지 함께 다루는 \n 상설전입니다.",
        location: "서울 도시 건축 전시관",
        date: "2020, 10",
        category: "Interactive Media, \n 3D Projection Mapping",
        role: "Planning, Producing, Shoot \n Making, Development",
        iframe: [

        ],
        still: "STILLS",
        images: [
            "/img/works/archive/4/1.jpg",
            "/img/works/archive/4/2.jpg",
            "/img/works/archive/4/3.jpg",
            "/img/works/archive/4/4.jpg",
            "/img/works/archive/4/5.jpg",
            "/img/works/archive/4/6.jpg",
            "/img/works/archive/4/7.jpg",
        ],
        headerImage: "/img/works/archive/4/1-1.jpg",
    },
    {
        id: 5,
        title: "한양도성의 훼손과 탄생",
        subTitle: "한양도성박물관 \n Museum of Korean History",
        h2: "한양도성의 훼손과 탄생",
        h3: "500년 동안 같은 자리에서 한양 - 경성 - 서울의 역사를 거쳐온 \n 한양도성의 동쪽 대문 '흥인지문' 이 도시가 겪어온 일련의 순간들을 \n 흥인지문을 통해 돌아보는 특별전입니다.",
        location: "한양도성박물관",
        date: "2020, 09",
        category: "3D Motion Graphic, \n 3D Projection Mapping",
        role: "Planning, Producing, Making",
        iframe: [
            "https://www.youtube.com/embed/QRQGI3uv1WA"
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/5/1.jpg",
            "/img/works/archive/5/2.jpg",
            "/img/works/archive/5/3.jpg",
            "/img/works/archive/5/4.jpg",
            "/img/works/archive/5/5.jpg",
            "/img/works/archive/5/6.jpg",
        ],
        headerImage: "/img/works/archive/5/1-1.jpg",
    },
    {
        id: 6,
        title: "숙종대왕 호시절에",
        subTitle: "국립고궁박물관 \n Museum of Korean History",
        h2: "숙종대왕 호시절에",
        h3: "숙종대왕이 통치하던 조선후기, 숙종의 업적과 그를 둘러싼 설화 등을 \n 바탕으로 그 시대의 역사를 들여다보는 특별전입니다.",
        location: "국립고궁박물관",
        date: "2020, 05",
        category: "Animation, \n Projection Mapping, Kiosk",
        role: "Planning, Producing, Making \n Development",
        iframe: [
            "https://www.youtube.com/embed/OgUKLrNG2A4",
            "https://www.youtube.com/embed/Vhl0geMWdJg",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/6/1.jpg",
            "/img/works/archive/6/2.jpg",
            "/img/works/archive/6/3.jpg",
            "/img/works/archive/6/4.jpg",
            "/img/works/archive/6/5.jpg",
            "/img/works/archive/6/6.jpg",
            "/img/works/archive/6/7.jpg",
            "/img/works/archive/6/8.jpg",
            "/img/works/archive/6/9.jpg",
        ],
        headerImage: "/img/works/archive/6/1-1.jpg",
    },
    {
        id: 7,
        title: "오색영롱 - 한국 고대 유리와 신라",
        subTitle: "국립경주박물관 \n Gyeongju National Museum",
        h2: "오색영롱 - 한국 고대 유리와 신라",
        h3: "신라인이 아끼고 사랑한 유리를 중심으로 한국 고대유리의 \n 전반적 흐름을 조명하는 특별전입니다.",
        location: "국립경주박물관",
        date: "2020, 12",
        category: "Interactive Media, Animation, \n Documentary Film",
        role: "Planning, Producing, Shoot \n Making, Development",
        iframe: [
            "https://www.youtube.com/embed/er3TyOLmOp0"
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/7/1.jpg",
            "/img/works/archive/7/3.jpg",
            "/img/works/archive/7/2.jpg",
            "/img/works/archive/7/4.jpg",
            "/img/works/archive/7/5.jpg",
            "/img/works/archive/7/6.jpg",
            "/img/works/archive/7/7.jpg",
            "/img/works/archive/7/8.jpg",
            "/img/works/archive/7/9.jpg",
            "/img/works/archive/7/10.jpg",
            "/img/works/archive/7/11.jpg",
        ],
        headerImage: "/img/works/archive/7/8.jpg",
    },
    {
        id: 8,
        title: "오월 그날이 다시 오면",
        subTitle: "대한민국역사박물관 \n Museum of Korean History",
        h2: "오월 그날이 다시 오면",
        h3: "5.18 민주화운동 40주년을 맞이하여 그해 오월, \n 광주의 이야기를 담은 특별전입니다.",
        location: "대한민국역사박물관",
        date: "2020, 05",
        category: "3D Projection Mapping, \n Animation",
        role: "Planning, Producing, Making",
        iframe: [
            "https://www.youtube.com/embed/PY-ZarLhviA",
            "https://www.youtube.com/embed/ZRU6G_hnZWw",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/8/1.jpg",
            "/img/works/archive/8/2.jpg",
            "/img/works/archive/8/3.jpg",
            "/img/works/archive/8/4.jpg",
            "/img/works/archive/8/5.jpg",
            "/img/works/archive/8/6.jpg",
            "/img/works/archive/8/7.jpg",
            "/img/works/archive/8/8.jpg",
            "/img/works/archive/8/9.jpg",
            "/img/works/archive/8/10.jpg",
        ],
        headerImage: "/img/works/archive/8/1-1.jpg",
    },
    {
        id: 9,
        title: "서울은 소설의 주인공이다",
        subTitle: "서울역사박물관 \n Seoul Museum of History",
        h2: "서울은 소설의 주인공이다",
        h3: "한국전쟁 70주년, 4.19혁명 60주년을 맞이하여 해방 이후부터 \n 4.19혁명까지의 서울과 그 안의 삶을 문학을 통해 조명하는 \n 특별전입니다.",
        location: "서울역사박물관",
        date: "2020, 05",
        category: "Animation, Projection Mapping",
        role: "Planning, Producing, Making",
        iframe: [
            "https://www.youtube.com/embed/C0q6Uhcrm9A",
            "https://www.youtube.com/embed/5cNxGbv3ZHU",
            "https://www.youtube.com/embed/H2LBEvhdozw"
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/9/1.jpg",
            "/img/works/archive/9/2.jpg",
            "/img/works/archive/9/3.jpg",
            "/img/works/archive/9/4.jpg",
            "/img/works/archive/9/5.jpg",
            "/img/works/archive/9/6.jpg",
            "/img/works/archive/9/7.jpg",
            "/img/works/archive/9/8.jpg",
            "/img/works/archive/9/9.jpg",
            "/img/works/archive/9/10.jpg",
        ],
        headerImage: "/img/works/archive/9/1-1.jpg",
    },
    {
        id: 10,
        title: "수표교水標橋 - 한양에 비가 내리면",
        subTitle: "청계천박물관 \n Cheonggyecheon Museum",
        h2: "수표교水標橋 - 한양에 비가 내리면",
        h3: "조선시대 한양에 축조된 다리 중 원형 그대로 남아 있는 유일한 다리 \n 수표교. '수표교-한양에 비가내리면'은 수표교를 중심으로 당시의 \n 풍습, 문화 등 각양의 역사를 보여주는 특별전입니다.",
        location: "청계천박물관",
        date: "2019, 12",
        category: "Immersive Space, Animation, Kiosk",
        role: "Planning, Producing, Making, \n Development",
        iframe: [
            "https://www.youtube.com/embed/tEAGhx_I8Zk",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/10/1.jpg",
            "/img/works/archive/10/2.jpg",
            "/img/works/archive/10/3.jpg",
            "/img/works/archive/10/4.jpg",
            "/img/works/archive/10/5.jpg",
            "/img/works/archive/10/6.jpg",
            "/img/works/archive/10/7.jpg",
            "/img/works/archive/10/8.jpg",
            "/img/works/archive/10/9.jpg",
            "/img/works/archive/10/10.jpg",
        ],
        headerImage: "/img/works/archive/10/1-1.jpg",
    },
    {
        id: 11,
        title: "인간, 물질 그리고 변형 \n 핀란드 디자인 10,000년",
        subTitle: "국립중앙박물관  \n National Museum of Korea",
        h2: "인간, 물질 그리고 변형 \n 핀란드 디자인 10,000년",
        h3: "지난 10,000년 동안 핀란드 지역에서 변화무쌍하게 발전한 물질과 \n 문화, 기술을 단선적인 연대기, 시대 구분에 따른 분류를 벗어나 \n 새로운 관점으로 조명하고 분류한 전시입니다.",
        location: "국립중앙박물관",
        date: "2019, 12",
        category: "Immersive Space, Interactive Art, \n 3D Projection Mapping, \n Motion Graphic",
        role: "Planning, Producing, Making, \n Development",
        iframe: [
            "https://www.youtube.com/embed/rYne_iquCLo",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/11/1.jpg",
            "/img/works/archive/11/2.jpg",
            "/img/works/archive/11/3.jpg",
            "/img/works/archive/11/4.jpg",
            "/img/works/archive/11/5.jpg",
            "/img/works/archive/11/6.jpg",
            "/img/works/archive/11/7.jpg",
            "/img/works/archive/11/8.jpg",
            "/img/works/archive/11/9.jpg",
            "/img/works/archive/11/10.jpg",
            "/img/works/archive/11/11.jpg",
            "/img/works/archive/11/12.jpg",
            "/img/works/archive/11/13.jpg",
        ],
        headerImage: "/img/works/main/arc11.jpg",
    },
    {
        id: 12,
        title: "성균관과 반촌",
        subTitle: "서울역사박물관  \n Museum of Korean History",
        h2: "성균관과 반촌",
        h3: "조선시대 최고의 교육기관인 성균관과 원조 대학촌 '반촌'의 모습을 \n 들여다보며, 그곳에 살았던 유생과 반인의 이야기를 함께 소개하는 \n 특별전입니다.",
        location: "서울역사박물관",
        date: "2019, 11",
        category: "Projection Mapping, Animation, \n Shoot",
        role: "Planning, Producing, Making",
        iframe: [
            "https://www.youtube.com/embed/WEyUsCRZJXc",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/12/1.jpg",
            "/img/works/archive/12/2.jpg",
            "/img/works/archive/12/3.jpg",
            "/img/works/archive/12/4.jpg",
            "/img/works/archive/12/5.jpg",
            "/img/works/archive/12/6.jpg",
            "/img/works/archive/12/7.jpg",
            "/img/works/archive/12/8.jpg",
            "/img/works/archive/12/9.jpg",
            "/img/works/archive/12/10.jpg",
        ],
        headerImage: "/img/works/archive/12/1-1.jpg",
    },
    {
        id: 13,
        title: "소리, 역사를 담다",
        subTitle: "대한민국역사박물관  \n Museum of Korean History",
        h2: "소리, 역사를 담다",
        h3: "역사적인 순간과 사회의 변화를 포착한 소리에 주목하고 다양한 소리 \n 기록들을 통해 한국 근현대사에 담긴 이야기를 새로이 들어보는 \n 특별전입니다.",
        location: "대한민국역사박물관",
        date: "2019, 11",
        category: "Immersive Space, Animation, \n Shoot, Projection Mapping",
        role: "Planning, Producing, Making \n Development",
        iframe: [
            "https://www.youtube.com/embed/HJuRo9iC9Mc",
            "https://www.youtube.com/embed/o2QqTCKTIFE",
            "https://www.youtube.com/embed/6HCRe_GyWp4",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/13/1.jpg",
            "/img/works/archive/13/2.jpg",
            "/img/works/archive/13/3.jpg",
            "/img/works/archive/13/4.jpg",
            "/img/works/archive/13/5.jpg",
            "/img/works/archive/13/6.jpg",
            "/img/works/archive/13/7.jpg",
            "/img/works/archive/13/8.jpg",
            "/img/works/archive/13/9.jpg",
            "/img/works/archive/13/10.jpg",
            "/img/works/archive/13/11.jpg",
            "/img/works/archive/13/12.jpg",
            "/img/works/archive/13/13.jpg",
            "/img/works/archive/13/14.jpg",
            "/img/works/archive/13/15.jpg",
        ],
        headerImage: "/img/works/archive/13/1-1.jpg",
    },
    {
        id: 14,
        title: "四神사신이 호위하사, 백제 능산리 1호 \n 東下塚동하총",
        subTitle: "국립부여박물관  \n Buyeo National Museum",
        h2: "四神사신이 호위하사, 백제 능산리 1호 \n 東下塚동하총",
        h3: "능산리 1호 동하총을 정밀 재발굴하여 백제 왕릉을 체감할 수 있도록 \n 구성하고 고분문화에 대해 알리는 특별전입니다.",
        location: "국립부여박물관",
        date: "2019, 12",
        category: "Areal, Animation \n Projection Mapping \n Documentary Film",
        role: "Planning, Producing, Making \n Shoot",
        iframe: [

        ],
        still: "STILLS",
        images: [
            "/img/works/archive/14/1.jpg",
            "/img/works/archive/14/2.jpg",
            "/img/works/archive/14/3.jpg",
            "/img/works/archive/14/4.jpg",
            "/img/works/archive/14/5.jpg",
            "/img/works/archive/14/6.jpg",
            "/img/works/archive/14/7.jpg",
            "/img/works/archive/14/8.jpg",
            "/img/works/archive/14/9.jpg",
            "/img/works/archive/14/10.jpg",
            "/img/works/archive/14/11.jpg",
            "/img/works/archive/14/12.jpg",
        ],
        headerImage: "/img/works/archive/14/1-1.jpg",
    },
    {
        id: 15,
        title: "북촌, 열한 집의 오래된 기억",
        subTitle: "서울역사박물관 \n Seoul Museum of History",
        h2: "북촌, 열한 집의 오래된 기억",
        h3: "급변하는 북촌의 백년(1860~1960년) 동안 북촌에 거주했던 열한 가문 \n 주민들의 일상과 기억을 통해 북촌의 역사를 돌아보는 특별전입니다.",
        location: "서울역사박물관 ",
        date: "2019, 07",
        category: "Projection Mapping, Animation \n Shoot, Documentary Film",
        role: "Planning, Producing, Making \n Shoot",
        iframe: [
            "https://www.youtube.com/embed/d_6Oh2AUV0Y",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/15/1.jpg",
            "/img/works/archive/15/2.jpg",
            "/img/works/archive/15/3.jpg",
            "/img/works/archive/15/4.jpg",
            "/img/works/archive/15/5.jpg",
            "/img/works/archive/15/6.jpg",
            "/img/works/archive/15/7.jpg",
            "/img/works/archive/15/10.jpg",
            "/img/works/archive/15/8.jpg",
            "/img/works/archive/15/9.jpg",
        ],
        headerImage: "/img/works/archive/15/1-1.jpg",
    },
    {
        id: 16,
        title: "여의도공원 비행기 영상 쇼 \n '어느 소년 광복군의 비행'",
        subTitle: "서울여의도공원 \n Yeouido Park Monument for the Korean Air Force C-47",
        h2: "여의도공원 비행기 영상 쇼 \n '어느 소년 광복군의 비행'",
        h3: "한국 독립운동의 획을 그은 여러 사건들을 애니메이션으로 각색하여, \n 여의도 공원 'C-47' 비행기 동체에 맵핑한 미디어입니다.",
        location: "서울여의도공원",
        date: "2018, 07",
        category: "3D Projection Mapping, \n Animation",
        role: "Planning, Producing, Making",
        iframe: [
            "https://www.youtube.com/embed/etflKIyubZM",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/16/1.jpg",
            "/img/works/archive/16/2.jpg",
            "/img/works/archive/16/3.jpg",
            "/img/works/archive/16/4.jpg",
            "/img/works/archive/16/5.jpg",
            "/img/works/archive/16/6.jpg",
            "/img/works/archive/16/7.jpg",
            "/img/works/archive/16/8.jpg",
            "/img/works/archive/16/9.jpg",
            "/img/works/archive/16/10.jpg",
        ],
        headerImage: "/img/works/archive/16/1-1.jpg",
    },
    {
        id: 17,
        title: "무병장수의 별 노인성, 제주를 비추다",
        subTitle: "국립제주박물관 \n Jeju National Museum",
        h2: "무병장수의 별 노인성, 제주를 비추다",
        h3: "제주의 특별한 별 '노인성' 노인성에 얽힌 흥미로운 이야기와 더불어 \n 제주의 밤하늘을 오래도록 들여다볼 수 있는 힐링 공간을 제공하는 \n 특별전입니다.",
        location: "국립제주박물관",
        date: "2018, 07",
        category: "3D Projection Mapping, \n Animation",
        role: "Planning, Producing, Making",
        iframe: [

        ],
        still: "STILLS",
        images: [
            "/img/works/archive/17/1.jpg",
            "/img/works/archive/17/2.jpg",
            "/img/works/archive/17/3.jpg",
            "/img/works/archive/17/4.jpg",
            "/img/works/archive/17/5.jpg",
            "/img/works/archive/17/6.jpg",
            "/img/works/archive/17/7.jpg",
            "/img/works/archive/17/8.jpg",
        ],
        headerImage: "/img/works/archive/17/1-1.jpg",
    },
    {
        id: 18,
        title: "서울과 평양의 3·1운동",
        subTitle: "대한민국역사박물관 \n Museum of Korean History",
        h2: "서울과 평양의 3·1운동",
        h3: "3·1운동 100주년을 맞이하여, 서울과 평양에서 동시에 일어난 \n 3·1운동을 도시역사의 관점에서 조명한 특별전입니다.",
        location: "대한민국역사박물관",
        date: "2019, 03",
        category: "Interactive Media, Animation, \n Shoot, Projection Mapping",
        role: "Planning, Producing, Making \n System Design, Development",
        iframe: [
            "https://www.youtube.com/embed/Whp9TJXekhw",
            "https://www.youtube.com/embed/Y6spYKBUzm4",
            "https://www.youtube.com/embed/GBmeuuFuu-o",
            "https://www.youtube.com/embed/FPQ_NGP3I10",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/18/1.jpg",
            "/img/works/archive/18/2.jpg",
            "/img/works/archive/18/3.jpg",
            "/img/works/archive/18/4.jpg",
            "/img/works/archive/18/5.jpg",
            "/img/works/archive/18/6.jpg",
            "/img/works/archive/18/7.jpg",
            "/img/works/archive/18/8.jpg",
            "/img/works/archive/18/9.jpg",
            "/img/works/archive/18/10.jpg",
            "/img/works/archive/18/11.jpg",
        ],
        headerImage: "/img/works/archive/18/1-1.jpg",
    },
    {
        id: 19,
        title: "경강 -  광나루에서 양화진까지",
        subTitle: "서울역사박물관 \n Seoul Museum of History",
        h2: "경강 -  광나루에서 양화진까지",
        h3: "조선시대 한강인 '경강(京江)'의 상업활동과 경강 사람들의 역동적인 \n 이야기를 소개하는 기획전입니다.",
        location: "서울역사박물관",
        date: "2018, 11",
        category: "Animation, Projection Mapping, \n Documentary Film",
        role: "Planning, Producing, Making",
        iframe: [

        ],
        still: "STILLS",
        images: [
            "/img/works/archive/19/1.jpg",
            "/img/works/archive/19/2.jpg",
            "/img/works/archive/19/3.jpg",
            "/img/works/archive/19/4.jpg",
            "/img/works/archive/19/5.jpg",
            "/img/works/archive/19/6.jpg",
            "/img/works/archive/19/7.jpg",
            "/img/works/archive/19/8.jpg",
            "/img/works/archive/19/9.jpg",
            "/img/works/archive/19/10.jpg",
        ],
        headerImage: "/img/works/archive/19/1-1.jpg",
    },
    {
        id: 20,
        title: "메이드 인 청계천 대중문화, \n ‘빽판’의 시대",
        subTitle: "청계천박물관 \n Cheonggyecheon Museum",
        h2: "메이드 인 청계천 대중문화, \n ‘빽판’의 시대",
        h3: "청계천이 서울에서 대중과 대중문화에 끼친 역할을 조명하고, \n 1960∼80년대 청계천 세운상가를 중심으로 성행했던 문화의 \n 언더그라운드, 청계천일대의 추억을 만날 수 있는 특별전입니다.",
        location: "청계천박물관",
        date: "2018, 08",
        category: "Projection Mapping, \n Documentary Film",
        role: "Planning, Producing, Making",
        iframe: [
            "https://www.youtube.com/embed/je4S1VS-mxU",
            "https://www.youtube.com/embed/Xi7RUHT0SbY",
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/20/1.jpg",
            "/img/works/archive/20/2.jpg",
            "/img/works/archive/20/3.jpg",
            "/img/works/archive/20/4.jpg",
            "/img/works/archive/20/5.jpg",
        ],
        headerImage: "/img/works/archive/20/1-1.jpg",
    },
    {
        id: 21,
        title: "그들이 꿈꾸었던 나라",
        subTitle: "대한민국역사박물관 \n Museum of Korean History",
        h2: "그들이 꿈꾸었던 나라",
        h3: "1945년 광복에서부터 1948년 정부 수립에 이르기까지 사회의 \n 여러 영역에서 나타난새로운 사회의 모습과 이를 이룩하려 했던 의지와 노력을 \n 돌아보는 전시, 70년 전 대한민국 정부의 출발점을 돌아보는 \n 특별전입니다.",
        location: "대한민국역사박물관",
        date: "2018, 08",
        category: "Projection Mapping, \n Documentary Film",
        role: "Planning, Producing, Making",
        iframe: [
            "https://www.youtube.com/embed/db-uKK15N9Y"
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/21/1.jpg",
            "/img/works/archive/21/2.jpg",
            "/img/works/archive/21/3.jpg",
            "/img/works/archive/21/4.jpg",
            "/img/works/archive/21/5.jpg",
            "/img/works/archive/21/6.jpg",
            "/img/works/archive/21/7.jpg",
            "/img/works/archive/21/8.jpg",
        ],
        headerImage: "/img/works/archive/21/1-1.jpg",
    },
    {
        id: 22,
        title: "개태사開泰寺 - 태평성대 고려高麗를 열다",
        subTitle: "국립부여박물관 \n Buyeo National Museum",
        h2: "개태사開泰寺 - 태평성대 고려高麗를 열다",
        h3: "고려의 번영을 염원한 태조 왕건의 호국 의지와 이를 증명하는 \n 개태사의 위엄을 알리는 특별전입니다.",
        location: "국립부여박물관",
        date: "2018, 05",
        category: "Projection Mapping",
        role: "Planning, Producing, Making",
        iframe: [
            "https://www.youtube.com/embed/VrOY9kpeQKo"
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/22/1.jpg",
            "/img/works/archive/22/2.jpg",
            "/img/works/archive/22/3.jpg",
            "/img/works/archive/22/4.jpg",
            "/img/works/archive/22/5.jpg",
            "/img/works/archive/22/6.jpg",
            "/img/works/archive/22/7.jpg",
        ],
        headerImage: "/img/works/archive/22/1-1.jpg",
    },
    {
        id: 23,
        title: "다시 보는 청계천 – 구와바라 시세이 사진전",
        subTitle: "청계천박물관 \n Seoul City Architecture Exhibition Hall",
        h2: "다시 보는 청계천 – 구와바라 시세이 사진전",
        h3: "한국의 근현대사를 취재해온 다큐멘터리 사진작가 구와바라 시세이가 \n 찍은 청계천을 소개하는 특별전입니다.",
        location: "청계천박물관",
        date: "2017, 04",
        category: "Projection Mapping, \n Documentary Film",
        role: "Planning, Producing, Making",
        iframe: [
            "https://www.youtube.com/embed/zAmk7-mw91E"
        ],
        still: "STILLS",
        images: [
            "/img/works/archive/23/1.jpg",
            "/img/works/archive/23/2.jpg",
            "/img/works/archive/23/3.jpg",
            "/img/works/archive/23/4.jpg",
            "/img/works/archive/23/5.jpg",
            "/img/works/archive/23/6.jpg",
            "/img/works/archive/23/7.jpg",
            "/img/works/archive/23/8.jpg",
        ],
        headerImage: "/img/works/archive/23/1-1.jpg",
    },
];
